agent:
  learning_rate: 0.1
  discount_factor: 0.95
  epsilon: 1.0
  decay_rate: 0.995
  value_per_click: 10.0

environment:
  gui_mode: false

simulator:
  num_competitors: 5
  initial_budget: 1000.0
  value_per_click: 10.0
  bid_distribution: 'normal'
  mean_bid: 50.0
  std_dev: 10.0

rewards:
  max_budget_consumption_per_auction: 0.25
  stop_penalty_percent: 0.1
  stop_penalty_decay: 0.5