agent:
  alpha: 0.1  # learning rate
  gamma: 0.9  # discount factor
  epsilon: 1.0  # initial exploration rate
  epsilon_decay: 0.99
  epsilon_min: 0.01
  num_actions: 5  # corresponds to [-10, -5, 0, 5, 10]

simulator:
  initial_budget: 1000
  # Note: priority_keywords will be prompted from user, this is just default
  priority_keywords: ['A', 'B', 'C']